package com.ducdiep.bookmarket.base

const val TABLE_USERS = "Users"
const val TABLE_BOOKS = "Books"
const val TABLE_CATEGORIES = "Categories"
const val TABLE_DISCOUNT_CODE = "DiscountCodes"
const val TABLE_MESSAGE = "Messages"
const val TABLE_ORDER = "Orders"
const val TABLE_ORDER_DETAIL = "OrderDetails"
const val TABLE_PRODUCT_RATING = "ProductRatings"
const val ROLE_ADMIN = "admin"
const val ROLE_CUSTOMER = "customer"
const val IMG_DEFAULT_MALE = "https://firebasestorage.googleapis.com/v0/b/bookmarket-12997.appspot.com/o/images%2Fuser_avatar%2Fdefaultnam.jpg?alt=media&token=a53f316d-eb76-4ca6-964b-f52eb8e6c4f8"
const val IMG_DEFAULT_FEMALE = "https://firebasestorage.googleapis.com/v0/b/bookmarket-12997.appspot.com/o/images%2Fuser_avatar%2Fdefaultnu.jpg?alt=media&token=33e8c633-9600-4de5-86ef-a3d5d9660739"
const val KEY_HOME_FRAGMENT = "HomeFragment"
const val KEY_CART_FRAGMENT = "CartFragment"
const val KEY_CATEGORY_FRAGMENT = "CategoryFragment"
const val KEY_USER_INFOR_FRAGMENT = "UserInfoFragment"
const val DATE_TIME_FORMAT = "dd-MM-yyyy hh:mm:ss"
const val DATE_FORMAT = "dd-MM-yyyy"
const val KEY_MANAGE_BOOK = "ManageBook"
const val KEY_MANAGE_ACCOUNT = "ManageAccount"
const val KEY_MANAGE_CATEGORY = "ManageCategory"
const val KEY_MANAGE_ORDER = "ManageOrder"
